[workspace]
resolver = "3"
members = [".", "codegen", "app", "core", "derive", "math"]
[workspace.package]
authors = ["algosul <hxb.air@gmail.com>"]
repository = "https://github.com/algosul/algosul-rs"
keywords = ["algosul"]
license-file = "LICENSE"
edition = "2024"
description = "Some user-friendly yet personalized tools"
readme = "README.md"

[workspace.dependencies]
algosul-app.path = "app"
algosul-derive.path = "derive"
algosul-core.path = "core"
algosul-math.path = "math"
algosul-codegen.path = "codegen"
image = "0.25.6"
sys-locale = "0.3.2"
strfmt = "0.2.5"
env_logger = "0.11.8"
reqwest = "0.13.3"
log = "0.4.27"
toml = "1.1.2"
serde = "1.0.219"
bytes = "1.10.1"
tokio = "1.46.1"
rayon = "1.10.0"
itertools = "0.14.0"
regex = "1.11.1"
thiserror = "2.0.18"
rfd = "0.17.2"
strum = "0.28.0"
glob = "0.3.3"
proc-macro2 = "1.0.101"
syn = "2.0.106"
quote = "1.0.40"
num = "0.4.3"
num-traits = "0.2.19"
unicode-xid = "0.2.6"

[package]
name = "algosul"
version = "0.0.5"
authors.workspace = true
repository.workspace = true
keywords.workspace = true
license-file.workspace = true
edition.workspace = true
description.workspace = true
readme.workspace = true
build = "build.rs"
autotests = false
autobins = false
autobenches = false
autoexamples = false

[lib]
name = "algosul"
crate-type = ["rlib"]

[[test]]
name = "asset"
path = "tests/asset.rs"
required-features = ["asset-image", "asset-text", "rayon"]

[features]
default = ["app-apps", "asset"]

serde = ["algosul-app/serde", "algosul-math/serde"]

derive = ["dep:algosul-derive"]

app = ["dep:algosul-app"]
app-apps = ["algosul-app/apps"]

asset = ["dep:toml"]
asset-text = ["asset", "dep:strfmt", "dep:itertools"]
asset-image = ["asset", "dep:image"]

math = ["dep:algosul-math"]
math-color = ["math", "algosul-math/color"]

process = []

utils = ["dep:rfd"]
utils-tokio = ["utils", "dep:tokio", "dep:bytes"]

langs = []

no_std = ["algosul-core/no_std", "algosul-app/no_std", "algosul-math/no_std"]

unstable = []

[package.metadata.docs.rs]
rustdoc-args = ["-cfg", "docsrs"]

[dependencies]
algosul-app = { workspace = true, optional = true, public = true }
algosul-derive = { workspace = true, optional = true, features = [] }
algosul-core = { workspace = true, features = [], public = true }
algosul-math = { workspace = true, features = [
], optional = true, public = true }

image = { workspace = true, features = ["serde"], optional = true }
sys-locale = { workspace = true, optional = true }
strfmt = { workspace = true, optional = true, public = true }
env_logger = { workspace = true }
reqwest = { workspace = true, features = ["blocking"], optional = true }
log = { workspace = true, features = ["serde", "kv_serde"] }
toml = { workspace = true, optional = true }
serde = { workspace = true, features = ["derive"] }
bytes = { workspace = true, features = ["serde"], optional = true }
tokio = { workspace = true, features = [
    "process",
    "io-util",
    "rt",
    "macros",
    "rt-multi-thread",
], optional = true }
rayon = { workspace = true, features = [], optional = true }
itertools = { workspace = true, features = [], optional = true }
regex = { workspace = true, features = [], optional = true }
thiserror = { workspace = true, features = [], optional = true }
rfd = { workspace = true, optional = true }
strum = { workspace = true, features = ["derive"] }

[build-dependencies]
algosul-codegen = { workspace = true }
proc-macro2 = { workspace = true }
syn = { workspace = true, features = ["full"] }
log = { workspace = true, features = [] }
env_logger = { workspace = true, features = [] }
glob = { workspace = true, features = [] }
