[package]
name = "algosul-derive"
version.workspace = true
authors.workspace = true
repository.workspace = true
keywords.workspace = true
license-file.workspace = true
edition.workspace = true
description.workspace = true
readme.workspace = true

[lib]
proc-macro = true

[features]
default = []

unstable = [
    "algosul-core/unstable",
    "proc-macro2/nightly",
]

wrapper = ["algosul-core/wrapper"]

[[test]]
name = "wrapper"
required-features = ["wrapper"]

[dependencies]
algosul-core = { workspace = true, public = true }
proc-macro2.workspace = true
proc-macro-warning.workspace = true
quote.workspace = true
syn = { workspace = true, features = ["full"] }
