[package]
name = "algosul-math"
version.workspace = true
authors.workspace = true
repository.workspace = true
keywords.workspace = true
license-file.workspace = true
edition.workspace = true
description.workspace = true
readme.workspace = true

[features]
default = []

std = ["algosul-core/std"]
std-unstable-matrix = [
    "std",
    "unstable",
    "__feature-portable_simd",
    "__feature-generic_const_args",
    "algosul-core/wrapper"
]
std-unstable-vector = [
    "std",
    "unstable",
    "__feature-portable_simd",
    "algosul-core/wrapper"
]
std-unstable-color = [
    "std",
    "unstable",
    "__feature-portable_simd",
    "algosul-core/wrapper"
]

unstable = []
unstable-full = [
    "unstable",
    "std-unstable-matrix",
    "std-unstable-vector",
    "std-unstable-color",
]

__feature-portable_simd = ["unstable"]
__feature-generic_const_args = ["unstable"]

serde = []

[dependencies]
algosul-core = { workspace = true, default-features = false, public = true }