[package]
name = "algosul-derive-util"
version.workspace = true
authors.workspace = true
repository.workspace = true
keywords.workspace = true
license-file.workspace = true
edition.workspace = true
description.workspace = true
readme.workspace = true

[features]
default = []

unstable = []

[dependencies]
algosul-core = { workspace = true, features = ["wrapper", "util"], public = true }
proc-macro2 = { workspace = true, public = true }
proc-macro-warning = { workspace = true, public = true }
quote = { workspace = true, public = true }
syn = { workspace = true, public = true }