[package]
name = "algosul-core"
version.workspace = true
authors.workspace = true
repository.workspace = true
keywords.workspace = true
license-file.workspace = true
edition.workspace = true
description.workspace = true
readme.workspace = true

[features]
default = []

std = ["serde/std", "thiserror/std", "uuid/std"]
unstable = []
unstable-full = ["unstable"]

__feature-const_trait_impl = ["unstable"]

serde = ["dep:serde"]

i18n = ["dep:unic-langid", "dep:unic-langid-impl"]
i18n-fluent = ["i18n", "dep:fluent"]

util = []
util-async = ["util"]
util-std = ["util", "std", "wrapper"]

wrapper = []

module = ["std"]

message = ["module"]

[package.metadata.docs.rs]
rustdoc-args = ["-cfg", "docsrs"]

[dependencies]
serde = { workspace = true, optional = true }
thiserror.workspace = true
fluent = { workspace = true, public = true, optional = true }
unic-langid = { workspace = true, public = true, optional = true }
unic-langid-impl = { workspace = true, public = true, optional = true }
uuid = { workspace = true, optional = true }