[package]
name = "algosul-core"
version = "0.0.5"
authors.workspace = true
repository.workspace = true
keywords.workspace = true
license-file.workspace = true
edition.workspace = true
description.workspace = true
readme.workspace = true

[features]
default = []

[package.metadata.docs.rs]
rustdoc-args = ["-cfg", "docsrs"]

[dependencies]
proc-macro2 = { workspace = true, public = true }
quote = { workspace = true, public = true }
syn = { workspace = true, features = ["full"], public = true }
unicode-xid = { workspace = true, public = true }
glob = { workspace = true, public = true }
tokio = { workspace = true, features = ["full"], public = true }
bytes = { workspace = true, public = true }
thiserror.workspace = true