[package]
name = "algosul-app"
version = "0.0.5"
authors.workspace = true
repository.workspace = true
keywords.workspace = true
license-file.workspace = true
edition.workspace = true
description.workspace = true
readme.workspace = true

[features]
default = []
serde = ["dep:serde"]
apps = ["dep:tokio", "dep:regex", "dep:thiserror"]

[dependencies]
algosul-core = { workspace = true, public = true }
algosul-derive = { workspace = true, public = true }
tokio = { workspace = true, features = [
    "full"
], optional = true, public = true }
regex = { workspace = true, optional = true, public = true }
thiserror = { workspace = true, optional = true }
serde = { workspace = true, features = ["derive"], optional = true }
syn = { workspace = true, public = true }
unicode-xid.workspace = true
reqwest = { workspace = true, public = true }
env_logger.workspace = true
toml = { workspace = true, public = true }
log.workspace = true